apiVersion: v1
kind: Pod
metadata:
  name: pod-serving-{{ .Iteration }}-{{ .Replica }}-{{.JobName }}
  namespace: serving-ns
  annotations:
    k8s.ovn.org/routing-namespaces: served-ns-{{ .Iteration }}
    k8s.ovn.org/routing-network: sriov-net-ens2f0
    k8s.ovn.org/bfd-enabled: "true"
    #k8s.v1.cni.cncf.io/networks: sriov-net-ens2f1-1
    k8s.v1.cni.cncf.io/networks: |-
      [{ "name": "sriov-net-ens2f0", "ips": [ "192.168.{{ add 216 .Replica }}.{{ .Iteration }}/21" ]}]
    k8s.v1.cni.cncf.io/network-status: |-
      [{
          "name": "sriov-net-ens2f0",
          "interface": "net1",
          "ips" : [
              "192.168.{{ add 216 .Replica }}.{{ .Iteration }}"
          ],
          "dns": {}
      }
      ]
spec:
  containers:
  - name: bfd
    image: quay.io/fpaoline/ovnkbfdtest:0.2
    command: ["/bin/sh","-c"]
    args: ["/usr/lib/frr/frrinit.sh start && sleep infinity"]
    ports:
    - containerPort: 3784
      protocol: UDP
    securityContext:
      privileged: true
    volumeMounts:
    - name: config-volume
      mountPath: /etc/frr
  volumes:
    - name: config-volume
      configMap:
        name: frr
  nodeSelector:
    serving: ""


